version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  tests: false

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - bodyclose
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
    govet:
      enable:
        - shadow
    misspell:
      locale: US

formatters:
  enable:
    - gofmt
    - goimports

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 50
  # Maximum count of issues with the same text
  max-same-issues: 10
