name: Bug Report
description: Report bugs or issues.
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! The more info you provide, the more we can help you.

  - type: checkboxes
    attributes:
      label: Check existing issues
      description: By submitting this issue, you checked there isn't already an issue for this bug.
      options:
        - label: I checked there isn't [already an issue](https://github.com/ChefBingbong/viem-go/issues) for the bug I encountered.
          required: true

  - type: input
    attributes:
      label: viem-go Version
      description: What version of viem-go are you using?
      placeholder: x.y.z (do not write `latest`)
    validations:
      required: true

  - type: input
    attributes:
      label: Go Version
      description: What version of Go are you using? (run `go version`)
      placeholder: go1.24.0
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps or code snippets to reproduce the behavior.
      placeholder: |
        1. Create a client with...
        2. Call method...
        3. Observe error...
    validations:
      required: false

  - type: textarea
    attributes:
      label: Code Example
      description: Please provide a minimal code example that reproduces the issue.
      render: go
    validations:
      required: false

  - type: textarea
    attributes:
      label: Error Output
      description: If applicable, paste the full error message or stack trace.
      render: shell
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Any other context about the problem? OS, environment details, related issues?

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
