// Code generated by viemgen. DO NOT EDIT.
package contract_test

import (
	"context"
	"errors"
	"math/big"

	"github.com/ethereum/go-ethereum/common"

	"github.com/ChefBingbong/viem-go/client"
	"github.com/ChefBingbong/viem-go/contract"
	"github.com/ChefBingbong/viem-go/types"
)

// Suppress unused import warnings
var (
	_ = big.NewInt
	_ = common.Address{}
	_ types.Transaction
)

// ContractABI is the ABI of the Erc200 contract.
var ContractABI = `[
    {
        "constant": true,
        "inputs": [],
        "name": "name",
        "outputs": [
            {
                "name": "",
                "type": "string"
            }
        ],
        "type": "function"
    },
    {
        "constant": true,
        "inputs": [],
        "name": "symbol",
        "outputs": [
            {
                "name": "",
                "type": "string"
            }
        ],
        "type": "function"
    },
    {
        "constant": true,
        "inputs": [],
        "name": "decimals",
        "outputs": [
            {
                "name": "",
                "type": "uint8"
            }
        ],
        "type": "function"
    },
    {
        "constant": true,
        "inputs": [],
        "name": "totalSupply",
        "outputs": [
            {
                "name": "",
                "type": "uint256"
            }
        ],
        "type": "function"
    },
    {
        "constant": true,
        "inputs": [
            {
                "name": "owner",
                "type": "address"
            }
        ],
        "name": "balanceOf",
        "outputs": [
            {
                "name": "",
                "type": "uint256"
            }
        ],
        "type": "function"
    },
    {
        "constant": true,
        "inputs": [
            {
                "name": "owner",
                "type": "address"
            },
            {
                "name": "spender",
                "type": "address"
            }
        ],
        "name": "allowance",
        "outputs": [
            {
                "name": "",
                "type": "uint256"
            }
        ],
        "type": "function"
    },
    {
        "constant": false,
        "inputs": [
            {
                "name": "to",
                "type": "address"
            },
            {
                "name": "value",
                "type": "uint256"
            }
        ],
        "name": "transfer",
        "outputs": [
            {
                "name": "",
                "type": "bool"
            }
        ],
        "type": "function"
    },
    {
        "constant": false,
        "inputs": [
            {
                "name": "spender",
                "type": "address"
            },
            {
                "name": "value",
                "type": "uint256"
            }
        ],
        "name": "approve",
        "outputs": [
            {
                "name": "",
                "type": "bool"
            }
        ],
        "type": "function"
    },
    {
        "constant": false,
        "inputs": [
            {
                "name": "from",
                "type": "address"
            },
            {
                "name": "to",
                "type": "address"
            },
            {
                "name": "value",
                "type": "uint256"
            }
        ],
        "name": "transferFrom",
        "outputs": [
            {
                "name": "",
                "type": "bool"
            }
        ],
        "type": "function"
    },
    {
        "anonymous": false,
        "inputs": [
            {
                "indexed": true,
                "name": "from",
                "type": "address"
            },
            {
                "indexed": true,
                "name": "to",
                "type": "address"
            },
            {
                "indexed": false,
                "name": "value",
                "type": "uint256"
            }
        ],
        "name": "Transfer",
        "type": "event"
    },
    {
        "anonymous": false,
        "inputs": [
            {
                "indexed": true,
                "name": "owner",
                "type": "address"
            },
            {
                "indexed": true,
                "name": "spender",
                "type": "address"
            },
            {
                "indexed": false,
                "name": "value",
                "type": "uint256"
            }
        ],
        "name": "Approval",
        "type": "event"
    }
]`

// ============================================================================
// Typed Method Descriptors
// ============================================================================

// Erc200Methods defines typed method descriptors for the Erc200 contract.
type Erc200Methods struct {
	Decimals     contract.ReadMethod[uint8]
	TotalSupply  contract.ReadMethod[*big.Int]
	BalanceOf    contract.ReadMethod[*big.Int]
	Transfer     contract.WriteMethod
	Name         contract.ReadMethod[string]
	Symbol       contract.ReadMethod[string]
	Approve      contract.WriteMethod
	Allowance    contract.ReadMethod[*big.Int]
	TransferFrom contract.WriteMethod
}

// Methods is the typed method descriptors instance for Erc200.
var Methods = Erc200Methods{
	Decimals:     contract.ReadMethod[uint8]{Name: "decimals"},
	TotalSupply:  contract.ReadMethod[*big.Int]{Name: "totalSupply"},
	BalanceOf:    contract.ReadMethod[*big.Int]{Name: "balanceOf"},
	Transfer:     contract.WriteMethod{Name: "transfer"},
	Name:         contract.ReadMethod[string]{Name: "name"},
	Symbol:       contract.ReadMethod[string]{Name: "symbol"},
	Approve:      contract.WriteMethod{Name: "approve"},
	Allowance:    contract.ReadMethod[*big.Int]{Name: "allowance"},
	TransferFrom: contract.WriteMethod{Name: "transferFrom"},
}

// ============================================================================
// Contract Binding
// ============================================================================

// Erc200 is a binding to the Erc200 contract.
type Erc200 struct {
	contract *contract.Contract
	M        Erc200Methods // Typed method descriptors
}

// New creates a new Erc200 contract binding.
func New(address common.Address, c *client.PublicClient) (*Erc200, error) {
	cont, err := contract.NewContract(address, []byte(ContractABI), c)
	if err != nil {
		return nil, err
	}
	return &Erc200{contract: cont, M: Methods}, nil
}

// MustNew creates a new Erc200 contract binding, panicking on error.
func MustNew(address common.Address, c *client.PublicClient) *Erc200 {
	cont, err := New(address, c)
	if err != nil {
		panic(err)
	}
	return cont
}

// Address returns the contract address.
func (c *Erc200) Address() common.Address {
	return c.contract.Address()
}

// Contract returns the underlying contract instance.
func (c *Erc200) Contract() *contract.Contract {
	return c.contract
}

// Decimals calls the decimals function.
// Solidity: decimals()
func (c *Erc200) Decimals(ctx context.Context) (uint8, error) {
	result, err := c.contract.Read(ctx, "decimals")
	if err != nil {
		return 0, err
	}

	if len(result) == 0 {
		return 0, errors.New("Contract read returned no data")
	}

	return result[0].(uint8), nil

}

// TotalSupply calls the totalSupply function.
// Solidity: totalSupply()
func (c *Erc200) TotalSupply(ctx context.Context) (*big.Int, error) {
	result, err := c.contract.Read(ctx, "totalSupply")
	if err != nil {
		return nil, err
	}

	return result[0].(*big.Int), nil
}

// BalanceOf calls the balanceOf function.
// Solidity: balanceOf(address)
func (c *Erc200) BalanceOf(ctx context.Context, owner common.Address) (*big.Int, error) {
	result, err := c.contract.Read(ctx, "balanceOf", owner)
	if err != nil {
		return nil, err
	}

	return result[0].(*big.Int), nil
}

// PrepareTransfer prepares a transaction for the transfer function.
// Solidity: transfer(address,uint256)
func (c *Erc200) PrepareTransfer(ctx context.Context, opts contract.WriteOptions, to common.Address, value *big.Int) (*types.Transaction, error) {
	return c.contract.PrepareTransaction(ctx, opts, "transfer", to, value)
}

// EstimateTransfer estimates gas for the transfer function.
func (c *Erc200) EstimateTransfer(ctx context.Context, opts contract.WriteOptions, to common.Address, value *big.Int) (uint64, error) {
	return c.contract.EstimateGas(ctx, opts, "transfer", to, value)
}

// Name calls the name function.
// Solidity: name()
func (c *Erc200) Name(ctx context.Context) (string, error) {
	result, err := c.contract.Read(ctx, "name")
	if err != nil {
		return "", err
	}

	return result[0].(string), nil
}

// Symbol calls the symbol function.
// Solidity: symbol()
func (c *Erc200) Symbol(ctx context.Context) (string, error) {
	result, err := c.contract.Read(ctx, "symbol")
	if err != nil {
		return "", err
	}

	return result[0].(string), nil
}

// PrepareApprove prepares a transaction for the approve function.
// Solidity: approve(address,uint256)
func (c *Erc200) PrepareApprove(ctx context.Context, opts contract.WriteOptions, spender common.Address, value *big.Int) (*types.Transaction, error) {
	return c.contract.PrepareTransaction(ctx, opts, "approve", spender, value)
}

// EstimateApprove estimates gas for the approve function.
func (c *Erc200) EstimateApprove(ctx context.Context, opts contract.WriteOptions, spender common.Address, value *big.Int) (uint64, error) {
	return c.contract.EstimateGas(ctx, opts, "approve", spender, value)
}

// Allowance calls the allowance function.
// Solidity: allowance(address,address)
func (c *Erc200) Allowance(ctx context.Context, owner common.Address, spender common.Address) (*big.Int, error) {
	result, err := c.contract.Read(ctx, "allowance", owner, spender)
	if err != nil {
		return nil, err
	}

	return result[0].(*big.Int), nil
}

// PrepareTransferFrom prepares a transaction for the transferFrom function.
// Solidity: transferFrom(address,address,uint256)
func (c *Erc200) PrepareTransferFrom(ctx context.Context, opts contract.WriteOptions, from common.Address, to common.Address, value *big.Int) (*types.Transaction, error) {
	return c.contract.PrepareTransaction(ctx, opts, "transferFrom", from, to, value)
}

// EstimateTransferFrom estimates gas for the transferFrom function.
func (c *Erc200) EstimateTransferFrom(ctx context.Context, opts contract.WriteOptions, from common.Address, to common.Address, value *big.Int) (uint64, error) {
	return c.contract.EstimateGas(ctx, opts, "transferFrom", from, to, value)
}

// Event types

// TransferEvent represents a Transfer event.
type TransferEvent struct {
	From  common.Address
	To    common.Address
	Value *big.Int
}

// ApprovalEvent represents a Approval event.
type ApprovalEvent struct {
	Owner   common.Address
	Spender common.Address
	Value   *big.Int
}
